CREATE OR REPLACE TYPE PRODUCTS_T_1 AS OBJECT (
    NAME VARCHAR2(50),
    PRICE INT,
    CATEGORY VARCHAR2(30)
) NOT FINAL;
/
CREATE OR REPLACE TYPE ORDERS_T_1 AS OBJECT (
    COUNTRY VARCHAR2(50)
) NOT FINAL;
/
CREATE OR REPLACE TYPE CUSTOMERS_T_1 AS OBJECT (
    NAME VARCHAR2(50),
    AGE INT
) NOT FINAL;
/

// CREATE

CREATE TABLE PRODUCTS (PID INT PRIMARY KEY, PRODUCT PRODUCTS_T_1);

CREATE TABLE ORDERS (ORDER_ID INT PRIMARY KEY, ORDER_O ORDERS_T_1, PID INT, CONSTRAINT FK_PRODUCT FOREIGN KEY (PID) REFERENCES PRODUCTS(PID));

CREATE TABLE CUSTOMERS (CID INT PRIMARY KEY, CUSTOMER CUSTOMERS_T_1, CUSTOMER_ORDER INT, CONSTRAINT FK_CUSTOMER_ORDER FOREIGN KEY (CUSTOMER_ORDER) REFERENCES ORDERS(ORDER_ID));

// INSERT/UPDATE

INSERT INTO PRODUCTS VALUES (1, PRODUCTS_T_1('számítógép', 500, 'elektronika'));
INSERT INTO PRODUCTS VALUES (2, PRODUCTS_T_1('mosógép', 30000, 'háztartási eszköz'));
INSERT INTO PRODUCTS VALUES (3, PRODUCTS_T_1('toll', 200, 'iskolai eszköz'));

SELECT P.PRODUCT.NAME FROM PRODUCTS P;

UPDATE PRODUCTS P SET P.PRODUCT.NAME = 'fülhallgató' WHERE P.PID = 1;

INSERT INTO ORDERS VALUES (1, ORDERS_T_1('HU'), 1);
INSERT INTO ORDERS VALUES (2, ORDERS_T_1('SK'), 3);

UPDATE ORDERS O SET O.ORDER_O.COUNTRY = 'RO' WHERE O.ORDER_ID = 2;

INSERT INTO CUSTOMERS VALUES (1, CUSTOMERS_T_1('Béla', 26), 1);
INSERT INTO CUSTOMERS VALUES (2, CUSTOMERS_T_1('Sára', 35), 2);

UPDATE CUSTOMERS C SET C.CUSTOMER.AGE = 46 WHERE C.CID = 1;

// QUERIES

// legolcsóbb termék
SELECT MIN(P.PRODUCT.PRICE) FROM PRODUCTS P;

// rendelések száma
SELECT COUNT(*) FROM ORDERS;

//termékek átlagáránál magasabb árú termékek
SELECT P.PRODUCT.NAME, P.PRODUCT.PRICE FROM PRODUCTS P WHERE P.PRODUCT.PRICE > (SELECT AVG(P.PRODUCT.PRICE) FROM PRODUCTS P);

// vásárlók - rendelések - termékek összerendelése
SELECT * FROM CUSTOMERS C INNER JOIN ORDERS O ON C.CUSTOMER_ORDER = O.ORDER_ID INNER JOIN PRODUCTS P ON O.PID = P.PID;